### ISSUE TITLE
프론트엔드 목요일까지 업무

### ISSUE THREAD

**Issue by Imjieunn** [MEDIFLIX-ST-A/FrontEnd#10]
**병록**
- [x] 오른쪽 사이드바 동적 구현
- [x] 투두리스트 구현 (사이드바 내부)
- [x] 화면 규격에 맞게 사이드바 삽입
- [x] 투두리스트 기능 구현
- [x] 오른쪽 사이드바 레이아웃(CSS로 완벽하게 구현)
- [x] AreaGraph 구현

**지은**
- [x] 도넛파이차트 구현
- [x] 지역별 총 시청시간 막대 그래프로 구현
- [x] 왼쪽 사이드바 CSS 디자인
- [x] 왼쪽 사이드바 페이지 이동
- [x] 서버에서 받은 데이터 넣기
- [x] 전체 레이아웃 다듬기(CSS)
- [x] 일간/주간/월간/연간 버튼 이벤트 처리
- [x] 신규/유저 토글 이벤트 처리
- [x] 프론트에서 박을 데이터 박아놓기

**Comment by devrokket** [comment]
😁
